version: '3'

services:
  combine:
    image: nginx
    container_name: combine
    depends_on:
        - back
        - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./front
    depends_on:
        - back
    ports:
      - 8082:80
  
  back:
    image: back
    container_name: back
    build:
      context: ./back
    ports:
      - 8083:80